version: '3'

services:
  app:
    build: .
    ports:
      - "3308:3308"
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
